/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uPMT;

import application.Main;
import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
